/**
 * Visningsetiketter för rollväljaren på startsidan.
 * Nyckeln är den kanoniska yrkeskategorin i `rates` (används fortfarande som
 * value vid prisuppslag) — värdet är den vardagliga benämningen som visas i UI.
 * Saknas en roll här faller vi tillbaka på den kanoniska texten.
 */
const ROLE_LABELS_5C: Record<string, string> = {
  // ── Sjuksköterskor ───────────────────────────────────────────────
  "Specialistsjuksköterska akutsjukvård": "Akutsjuksköterska",
  "Specialistsjuksköterska ambulanssjukvård": "Ambulanssjuksköterska",
  "Specialistsjuksköterska anestesi": "Anestesisjuksköterska",
  "Specialistsjuksköterska barn och ungdom": "Barnsjuksköterska",
  "Specialistsjuksköterska diabetesvård": "Diabetessjuksköterska",
  "Specialistsjuksköterska företagshälsovård": "Företagssjuksköterska",
  "Specialistsjuksköterska hjärtsjukvård": "Hjärtsjuksköterska",
  "Specialistsjuksköterska infektionssjukvård": "Infektionssjuksköterska",
  "Specialistsjuksköterska intensivvård": "IVA-sjuksköterska",
  "Specialistsjuksköterska kirurgisk vård": "Kirurgsjuksköterska",
  "Specialistsjuksköterska medicinsk vård": "Medicinsjuksköterska",
  "Specialistsjuksköterska ögonsjukvård": "Ögonsjuksköterska",
  "Specialistsjuksköterska onkologisk vård": "Onkologisjuksköterska",
  "Specialistsjuksköterska operationssjukvård": "Operationssjuksköterska",
  "Specialistsjuksköterska palliativ vård": "Palliativsjuksköterska",
  "Specialistsjuksköterska psykiatrisk vård": "Psykiatrisjuksköterska",
  "Specialistsjuksköterska vård av äldre": "Geriatriksjuksköterska",
  Sjuksköterska: "Grundutbildad sjuksköterska",

  // ── Läkare ───────────────────────────────────────────────────────
  "Specialistläkare akutsjukvård": "Akutläkare",
  "Specialistläkare allergologi": "Allergolog",
  "Specialistläkare allmänmedicin": "Allmänläkare",
  "Specialistläkare äldrepsykiatri": "Äldrepsykiater",
  "Specialistläkare anestesi och intensivvård": "Anestesiläkare",
  "Specialistläkare arbets- och miljömedicin": "Arbets- och miljömedicinare",
  "Specialistläkare arbetsmedicin": "Arbetsmedicinare",
  "Specialistläkare barn- och ungdomsallergologi": "Barnallergolog",
  "Specialistläkare barn- och ungdomshematologi och onkologi": "Barnonkolog",
  "Specialistläkare barn- och ungdomskardiologi": "Barnkardiolog",
  "Specialistläkare barn- och ungdomskirurgi": "Barnkirurg",
  "Specialistläkare barn- och ungdomsmedicin": "Barnläkare",
  "Specialistläkare barn- och ungdomsneurologi med habilitering": "Barnneurolog",
  "Specialistläkare barn- och ungdomspsykiatri": "BUP-läkare",
  "Specialistläkare beroendemedicin": "Beroendeläkare",
  "Specialistläkare endokrinologi och diabetologi": "Endokrinolog",
  "Specialistläkare geriatrik": "Geriatriker",
  "Specialistläkare gynekologisk onkologi": "Gynonkolog",
  "Specialistläkare handkirurgi": "Handkirurg",
  "Specialistläkare hematologi": "Hematolog",
  "Specialistläkare hörsel- och balansrubbningar": "Audiolog",
  "Specialistläkare hud- och könssjukdomar": "Dermatolog",
  "Specialistläkare infektionssjukdomar": "Infektionsläkare",
  "Specialistläkare internmedicin": "Internmedicinare",
  "Specialistläkare kardiologi": "Kardiolog",
  "Specialistläkare kärlkirurgi": "Kärlkirurg",
  "Specialistläkare kirurgi": "Kirurg",
  "Specialistläkare klinisk farmakologi": "Klinisk farmakolog",
  "Specialistläkare klinisk fysiologi": "Klinisk fysiolog",
  "Specialistläkare klinisk genetik": "Klinisk genetiker",
  "Specialistläkare klinisk immunologi och transfusionsmedicin": "Klinisk immunolog",
  "Specialistläkare klinisk kemi": "Klinisk kemist",
  "Specialistläkare klinisk mikrobiologi": "Klinisk mikrobiolog",
  "Specialistläkare klinisk neurofysiologi": "Klinisk neurofysiolog",
  "Specialistläkare klinisk patologi": "Patolog",
  "Specialistläkare lungsjukdomar": "Lungläkare",
  "Specialistläkare medicinsk gastroenterologi och hepatologi": "Gastroenterolog",
  "Specialistläkare neonatologi": "Neonatolog",
  "Specialistläkare neurokirurgi": "Neurokirurg",
  "Specialistläkare neurologi": "Neurolog",
  "Specialistläkare neuroradiologi": "Neuroradiolog",
  "Specialistläkare njurmedicin": "Nefrolog",
  "Specialistläkare nuklearmedicin": "Nuklearmedicinare",
  "Specialistläkare obstetrik och gynekologi": "Gynekolog",
  "Specialistläkare ögonsjukdomar": "Ögonläkare",
  "Specialistläkare onkologi": "Onkolog",
  "Specialistläkare öron-, näs- och halssjukdomar": "ÖNH-läkare",
  "Specialistläkare ortopedi": "Ortoped",
  "Specialistläkare palliativ medicin": "Palliativläkare",
  "Specialistläkare plastikkirurgi": "Plastikkirurg",
  "Specialistläkare psykiatri": "Psykiater",
  "Specialistläkare radiologi": "Radiolog",
  "Specialistläkare rättsmedicin": "Rättsläkare",
  "Specialistläkare rättspsykiatri": "Rättspsykiater",
  "Specialistläkare rehabiliteringsmedicin": "Rehabläkare",
  "Specialistläkare reumatologi": "Reumatolog",
  "Specialistläkare röst- och talrubbningar": "Foniater",
  "Specialistläkare skolhälsovård": "Skolläkare",
  "Specialistläkare smärtlindring": "Smärtläkare",
  "Specialistläkare socialmedicin": "Socialmedicinare",
  "Specialistläkare thoraxkirurgi": "Thoraxkirurg",
  "Specialistläkare urologi": "Urolog",
  "Specialistläkare vårdhygien": "Vårdhygienläkare",
};

export function roleLabel5c(role: string): string {
  return ROLE_LABELS_5C[role] ?? role;
}
