/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AterstallLosenordRouteImport } from './routes/aterstall-losenord'
import { Route as FaktasidorRouteImport } from './routes/faktasidor'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegistreraRouteImport } from './routes/registrera'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VanligaFragorRouteImport } from './routes/vanliga-fragor'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgentApiKeysRouteImport } from './routes/admin/agent-api-keys'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as BollnasLakareAlmRouteImport } from './routes/bollnas/lakare-alm'
import { Route as ConsultantLayoutRouteImport } from './routes/consultant/_layout'
import { Route as ConsultantForhandlaRouteImport } from './routes/consultant/forhandla'
import { Route as DevAnalyticsRouteImport } from './routes/dev/analytics'
import { Route as DevAnimationerRouteImport } from './routes/dev/animationer'
import { Route as DevLlmsCheckRouteImport } from './routes/dev/llms-check'
import { Route as KampanjRoleRouteImport } from './routes/kampanj/$role'
import { Route as RapportReportIdRouteImport } from './routes/rapport/$reportId'
import { Route as RapportAllmansjukskoterskaRouteImport } from './routes/rapport/allmansjukskoterska'
import { Route as RapportAnestesisjukskoterskaRouteImport } from './routes/rapport/anestesisjukskoterska'
import { Route as RapportLakareAllmanmedicinRouteImport } from './routes/rapport/lakare-allmanmedicin'
import { Route as RapportLegSjukskoterskaRouteImport } from './routes/rapport/leg-sjukskoterska'
import { Route as RapportLegSskRouteImport } from './routes/rapport/leg-ssk'
import { Route as RapportLegitimeradSjukskoterskaRouteImport } from './routes/rapport/legitimerad-sjukskoterska'
import { Route as RapportSjukskoterskaRouteImport } from './routes/rapport/sjukskoterska'
import { Route as RapportSskRouteImport } from './routes/rapport/ssk'
import { Route as RegionRegionRouteImport } from './routes/region/$region'
import { Route as ResultatLeadIdRouteImport } from './routes/resultat/$leadId'
import { Route as TimprisRoleRouteImport } from './routes/timpris/$role'
import { Route as ApiPublicBekraftaForslagRouteImport } from './routes/api/public/bekrafta-forslag'
import { Route as ApiPublicSendSignupConfirmationRouteImport } from './routes/api/public/send-signup-confirmation'
import { Route as ConsultantLayoutAvtalRouteImport } from './routes/consultant/_layout/avtal'
import { Route as ConsultantLayoutLoneanalysRouteImport } from './routes/consultant/_layout/loneanalys'
import { Route as ConsultantLayoutProfilRouteImport } from './routes/consultant/_layout/profil'
import { Route as LonSpecialtyCityRouteImport } from './routes/lon/$specialty/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AterstallLosenordRoute = AterstallLosenordRouteImport.update({
  id: '/aterstall-losenord',
  path: '/aterstall-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const FaktasidorRoute = FaktasidorRouteImport.update({
  id: '/faktasidor',
  path: '/faktasidor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistreraRoute = RegistreraRouteImport.update({
  id: '/registrera',
  path: '/registrera',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VanligaFragorRoute = VanligaFragorRouteImport.update({
  id: '/vanliga-fragor',
  path: '/vanliga-fragor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentApiKeysRoute = AdminAgentApiKeysRouteImport.update({
  id: '/admin/agent-api-keys',
  path: '/admin/agent-api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BollnasLakareAlmRoute = BollnasLakareAlmRouteImport.update({
  id: '/bollnas/lakare-alm',
  path: '/bollnas/lakare-alm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantLayoutRoute = ConsultantLayoutRouteImport.update({
  id: '/consultant/_layout',
  path: '/consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantForhandlaRoute = ConsultantForhandlaRouteImport.update({
  id: '/consultant/forhandla',
  path: '/consultant/forhandla',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAnalyticsRoute = DevAnalyticsRouteImport.update({
  id: '/dev/analytics',
  path: '/dev/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAnimationerRoute = DevAnimationerRouteImport.update({
  id: '/dev/animationer',
  path: '/dev/animationer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLlmsCheckRoute = DevLlmsCheckRouteImport.update({
  id: '/dev/llms-check',
  path: '/dev/llms-check',
  getParentRoute: () => rootRouteImport,
} as any)
const KampanjRoleRoute = KampanjRoleRouteImport.update({
  id: '/kampanj/$role',
  path: '/kampanj/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportReportIdRoute = RapportReportIdRouteImport.update({
  id: '/rapport/$reportId',
  path: '/rapport/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportAllmansjukskoterskaRoute =
  RapportAllmansjukskoterskaRouteImport.update({
    id: '/rapport/allmansjukskoterska',
    path: '/rapport/allmansjukskoterska',
    getParentRoute: () => rootRouteImport,
  } as any)
const RapportAnestesisjukskoterskaRoute =
  RapportAnestesisjukskoterskaRouteImport.update({
    id: '/rapport/anestesisjukskoterska',
    path: '/rapport/anestesisjukskoterska',
    getParentRoute: () => rootRouteImport,
  } as any)
const RapportLakareAllmanmedicinRoute =
  RapportLakareAllmanmedicinRouteImport.update({
    id: '/rapport/lakare-allmanmedicin',
    path: '/rapport/lakare-allmanmedicin',
    getParentRoute: () => rootRouteImport,
  } as any)
const RapportLegSjukskoterskaRoute = RapportLegSjukskoterskaRouteImport.update({
  id: '/rapport/leg-sjukskoterska',
  path: '/rapport/leg-sjukskoterska',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportLegSskRoute = RapportLegSskRouteImport.update({
  id: '/rapport/leg-ssk',
  path: '/rapport/leg-ssk',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportLegitimeradSjukskoterskaRoute =
  RapportLegitimeradSjukskoterskaRouteImport.update({
    id: '/rapport/legitimerad-sjukskoterska',
    path: '/rapport/legitimerad-sjukskoterska',
    getParentRoute: () => rootRouteImport,
  } as any)
const RapportSjukskoterskaRoute = RapportSjukskoterskaRouteImport.update({
  id: '/rapport/sjukskoterska',
  path: '/rapport/sjukskoterska',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportSskRoute = RapportSskRouteImport.update({
  id: '/rapport/ssk',
  path: '/rapport/ssk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRegionRoute = RegionRegionRouteImport.update({
  id: '/region/$region',
  path: '/region/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatLeadIdRoute = ResultatLeadIdRouteImport.update({
  id: '/resultat/$leadId',
  path: '/resultat/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimprisRoleRoute = TimprisRoleRouteImport.update({
  id: '/timpris/$role',
  path: '/timpris/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBekraftaForslagRoute =
  ApiPublicBekraftaForslagRouteImport.update({
    id: '/api/public/bekrafta-forslag',
    path: '/api/public/bekrafta-forslag',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendSignupConfirmationRoute =
  ApiPublicSendSignupConfirmationRouteImport.update({
    id: '/api/public/send-signup-confirmation',
    path: '/api/public/send-signup-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultantLayoutAvtalRoute = ConsultantLayoutAvtalRouteImport.update({
  id: '/avtal',
  path: '/avtal',
  getParentRoute: () => ConsultantLayoutRoute,
} as any)
const ConsultantLayoutLoneanalysRoute =
  ConsultantLayoutLoneanalysRouteImport.update({
    id: '/loneanalys',
    path: '/loneanalys',
    getParentRoute: () => ConsultantLayoutRoute,
  } as any)
const ConsultantLayoutProfilRoute = ConsultantLayoutProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ConsultantLayoutRoute,
} as any)
const LonSpecialtyCityRoute = LonSpecialtyCityRouteImport.update({
  id: '/lon/$specialty/$city',
  path: '/lon/$specialty/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/faktasidor': typeof FaktasidorRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/logga-in': typeof LoggaInRoute
  '/onboarding': typeof OnboardingRoute
  '/registrera': typeof RegistreraRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/admin/agent-api-keys': typeof AdminAgentApiKeysRoute
  '/admin/health': typeof AdminHealthRoute
  '/bollnas/lakare-alm': typeof BollnasLakareAlmRoute
  '/consultant': typeof ConsultantLayoutRouteWithChildren
  '/consultant/forhandla': typeof ConsultantForhandlaRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/animationer': typeof DevAnimationerRoute
  '/dev/llms-check': typeof DevLlmsCheckRoute
  '/kampanj/$role': typeof KampanjRoleRoute
  '/rapport/$reportId': typeof RapportReportIdRoute
  '/rapport/allmansjukskoterska': typeof RapportAllmansjukskoterskaRoute
  '/rapport/anestesisjukskoterska': typeof RapportAnestesisjukskoterskaRoute
  '/rapport/lakare-allmanmedicin': typeof RapportLakareAllmanmedicinRoute
  '/rapport/leg-sjukskoterska': typeof RapportLegSjukskoterskaRoute
  '/rapport/leg-ssk': typeof RapportLegSskRoute
  '/rapport/legitimerad-sjukskoterska': typeof RapportLegitimeradSjukskoterskaRoute
  '/rapport/sjukskoterska': typeof RapportSjukskoterskaRoute
  '/rapport/ssk': typeof RapportSskRoute
  '/region/$region': typeof RegionRegionRoute
  '/resultat/$leadId': typeof ResultatLeadIdRoute
  '/timpris/$role': typeof TimprisRoleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/bekrafta-forslag': typeof ApiPublicBekraftaForslagRoute
  '/api/public/send-signup-confirmation': typeof ApiPublicSendSignupConfirmationRoute
  '/consultant/avtal': typeof ConsultantLayoutAvtalRoute
  '/consultant/loneanalys': typeof ConsultantLayoutLoneanalysRoute
  '/consultant/profil': typeof ConsultantLayoutProfilRoute
  '/lon/$specialty/$city': typeof LonSpecialtyCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/faktasidor': typeof FaktasidorRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/logga-in': typeof LoggaInRoute
  '/onboarding': typeof OnboardingRoute
  '/registrera': typeof RegistreraRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/admin/agent-api-keys': typeof AdminAgentApiKeysRoute
  '/admin/health': typeof AdminHealthRoute
  '/bollnas/lakare-alm': typeof BollnasLakareAlmRoute
  '/consultant': typeof ConsultantLayoutRouteWithChildren
  '/consultant/forhandla': typeof ConsultantForhandlaRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/animationer': typeof DevAnimationerRoute
  '/dev/llms-check': typeof DevLlmsCheckRoute
  '/kampanj/$role': typeof KampanjRoleRoute
  '/rapport/$reportId': typeof RapportReportIdRoute
  '/rapport/allmansjukskoterska': typeof RapportAllmansjukskoterskaRoute
  '/rapport/anestesisjukskoterska': typeof RapportAnestesisjukskoterskaRoute
  '/rapport/lakare-allmanmedicin': typeof RapportLakareAllmanmedicinRoute
  '/rapport/leg-sjukskoterska': typeof RapportLegSjukskoterskaRoute
  '/rapport/leg-ssk': typeof RapportLegSskRoute
  '/rapport/legitimerad-sjukskoterska': typeof RapportLegitimeradSjukskoterskaRoute
  '/rapport/sjukskoterska': typeof RapportSjukskoterskaRoute
  '/rapport/ssk': typeof RapportSskRoute
  '/region/$region': typeof RegionRegionRoute
  '/resultat/$leadId': typeof ResultatLeadIdRoute
  '/timpris/$role': typeof TimprisRoleRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/bekrafta-forslag': typeof ApiPublicBekraftaForslagRoute
  '/api/public/send-signup-confirmation': typeof ApiPublicSendSignupConfirmationRoute
  '/consultant/avtal': typeof ConsultantLayoutAvtalRoute
  '/consultant/loneanalys': typeof ConsultantLayoutLoneanalysRoute
  '/consultant/profil': typeof ConsultantLayoutProfilRoute
  '/lon/$specialty/$city': typeof LonSpecialtyCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/faktasidor': typeof FaktasidorRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/logga-in': typeof LoggaInRoute
  '/onboarding': typeof OnboardingRoute
  '/registrera': typeof RegistreraRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vanliga-fragor': typeof VanligaFragorRoute
  '/admin/agent-api-keys': typeof AdminAgentApiKeysRoute
  '/admin/health': typeof AdminHealthRoute
  '/bollnas/lakare-alm': typeof BollnasLakareAlmRoute
  '/consultant/_layout': typeof ConsultantLayoutRouteWithChildren
  '/consultant/forhandla': typeof ConsultantForhandlaRoute
  '/dev/analytics': typeof DevAnalyticsRoute
  '/dev/animationer': typeof DevAnimationerRoute
  '/dev/llms-check': typeof DevLlmsCheckRoute
  '/kampanj/$role': typeof KampanjRoleRoute
  '/rapport/$reportId': typeof RapportReportIdRoute
  '/rapport/allmansjukskoterska': typeof RapportAllmansjukskoterskaRoute
  '/rapport/anestesisjukskoterska': typeof RapportAnestesisjukskoterskaRoute
  '/rapport/lakare-allmanmedicin': typeof RapportLakareAllmanmedicinRoute
  '/rapport/leg-sjukskoterska': typeof RapportLegSjukskoterskaRoute
  '/rapport/leg-ssk': typeof RapportLegSskRoute
  '/rapport/legitimerad-sjukskoterska': typeof RapportLegitimeradSjukskoterskaRoute
  '/rapport/sjukskoterska': typeof RapportSjukskoterskaRoute
  '/rapport/ssk': typeof RapportSskRoute
  '/region/$region': typeof RegionRegionRoute
  '/resultat/$leadId': typeof ResultatLeadIdRoute
  '/timpris/$role': typeof TimprisRoleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/bekrafta-forslag': typeof ApiPublicBekraftaForslagRoute
  '/api/public/send-signup-confirmation': typeof ApiPublicSendSignupConfirmationRoute
  '/consultant/_layout/avtal': typeof ConsultantLayoutAvtalRoute
  '/consultant/_layout/loneanalys': typeof ConsultantLayoutLoneanalysRoute
  '/consultant/_layout/profil': typeof ConsultantLayoutProfilRoute
  '/lon/$specialty/$city': typeof LonSpecialtyCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aterstall-losenord'
    | '/faktasidor'
    | '/integritetspolicy'
    | '/logga-in'
    | '/onboarding'
    | '/registrera'
    | '/unsubscribe'
    | '/vanliga-fragor'
    | '/admin/agent-api-keys'
    | '/admin/health'
    | '/bollnas/lakare-alm'
    | '/consultant'
    | '/consultant/forhandla'
    | '/dev/analytics'
    | '/dev/animationer'
    | '/dev/llms-check'
    | '/kampanj/$role'
    | '/rapport/$reportId'
    | '/rapport/allmansjukskoterska'
    | '/rapport/anestesisjukskoterska'
    | '/rapport/lakare-allmanmedicin'
    | '/rapport/leg-sjukskoterska'
    | '/rapport/leg-ssk'
    | '/rapport/legitimerad-sjukskoterska'
    | '/rapport/sjukskoterska'
    | '/rapport/ssk'
    | '/region/$region'
    | '/resultat/$leadId'
    | '/timpris/$role'
    | '/admin/'
    | '/api/public/bekrafta-forslag'
    | '/api/public/send-signup-confirmation'
    | '/consultant/avtal'
    | '/consultant/loneanalys'
    | '/consultant/profil'
    | '/lon/$specialty/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aterstall-losenord'
    | '/faktasidor'
    | '/integritetspolicy'
    | '/logga-in'
    | '/onboarding'
    | '/registrera'
    | '/unsubscribe'
    | '/vanliga-fragor'
    | '/admin/agent-api-keys'
    | '/admin/health'
    | '/bollnas/lakare-alm'
    | '/consultant'
    | '/consultant/forhandla'
    | '/dev/analytics'
    | '/dev/animationer'
    | '/dev/llms-check'
    | '/kampanj/$role'
    | '/rapport/$reportId'
    | '/rapport/allmansjukskoterska'
    | '/rapport/anestesisjukskoterska'
    | '/rapport/lakare-allmanmedicin'
    | '/rapport/leg-sjukskoterska'
    | '/rapport/leg-ssk'
    | '/rapport/legitimerad-sjukskoterska'
    | '/rapport/sjukskoterska'
    | '/rapport/ssk'
    | '/region/$region'
    | '/resultat/$leadId'
    | '/timpris/$role'
    | '/admin'
    | '/api/public/bekrafta-forslag'
    | '/api/public/send-signup-confirmation'
    | '/consultant/avtal'
    | '/consultant/loneanalys'
    | '/consultant/profil'
    | '/lon/$specialty/$city'
  id:
    | '__root__'
    | '/'
    | '/aterstall-losenord'
    | '/faktasidor'
    | '/integritetspolicy'
    | '/logga-in'
    | '/onboarding'
    | '/registrera'
    | '/unsubscribe'
    | '/vanliga-fragor'
    | '/admin/agent-api-keys'
    | '/admin/health'
    | '/bollnas/lakare-alm'
    | '/consultant/_layout'
    | '/consultant/forhandla'
    | '/dev/analytics'
    | '/dev/animationer'
    | '/dev/llms-check'
    | '/kampanj/$role'
    | '/rapport/$reportId'
    | '/rapport/allmansjukskoterska'
    | '/rapport/anestesisjukskoterska'
    | '/rapport/lakare-allmanmedicin'
    | '/rapport/leg-sjukskoterska'
    | '/rapport/leg-ssk'
    | '/rapport/legitimerad-sjukskoterska'
    | '/rapport/sjukskoterska'
    | '/rapport/ssk'
    | '/region/$region'
    | '/resultat/$leadId'
    | '/timpris/$role'
    | '/admin/'
    | '/api/public/bekrafta-forslag'
    | '/api/public/send-signup-confirmation'
    | '/consultant/_layout/avtal'
    | '/consultant/_layout/loneanalys'
    | '/consultant/_layout/profil'
    | '/lon/$specialty/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AterstallLosenordRoute: typeof AterstallLosenordRoute
  FaktasidorRoute: typeof FaktasidorRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  LoggaInRoute: typeof LoggaInRoute
  OnboardingRoute: typeof OnboardingRoute
  RegistreraRoute: typeof RegistreraRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VanligaFragorRoute: typeof VanligaFragorRoute
  AdminAgentApiKeysRoute: typeof AdminAgentApiKeysRoute
  AdminHealthRoute: typeof AdminHealthRoute
  BollnasLakareAlmRoute: typeof BollnasLakareAlmRoute
  ConsultantLayoutRoute: typeof ConsultantLayoutRouteWithChildren
  ConsultantForhandlaRoute: typeof ConsultantForhandlaRoute
  DevAnalyticsRoute: typeof DevAnalyticsRoute
  DevAnimationerRoute: typeof DevAnimationerRoute
  DevLlmsCheckRoute: typeof DevLlmsCheckRoute
  KampanjRoleRoute: typeof KampanjRoleRoute
  RapportReportIdRoute: typeof RapportReportIdRoute
  RapportAllmansjukskoterskaRoute: typeof RapportAllmansjukskoterskaRoute
  RapportAnestesisjukskoterskaRoute: typeof RapportAnestesisjukskoterskaRoute
  RapportLakareAllmanmedicinRoute: typeof RapportLakareAllmanmedicinRoute
  RapportLegSjukskoterskaRoute: typeof RapportLegSjukskoterskaRoute
  RapportLegSskRoute: typeof RapportLegSskRoute
  RapportLegitimeradSjukskoterskaRoute: typeof RapportLegitimeradSjukskoterskaRoute
  RapportSjukskoterskaRoute: typeof RapportSjukskoterskaRoute
  RapportSskRoute: typeof RapportSskRoute
  RegionRegionRoute: typeof RegionRegionRoute
  ResultatLeadIdRoute: typeof ResultatLeadIdRoute
  TimprisRoleRoute: typeof TimprisRoleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicBekraftaForslagRoute: typeof ApiPublicBekraftaForslagRoute
  ApiPublicSendSignupConfirmationRoute: typeof ApiPublicSendSignupConfirmationRoute
  LonSpecialtyCityRoute: typeof LonSpecialtyCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aterstall-losenord': {
      id: '/aterstall-losenord'
      path: '/aterstall-losenord'
      fullPath: '/aterstall-losenord'
      preLoaderRoute: typeof AterstallLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktasidor': {
      id: '/faktasidor'
      path: '/faktasidor'
      fullPath: '/faktasidor'
      preLoaderRoute: typeof FaktasidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrera': {
      id: '/registrera'
      path: '/registrera'
      fullPath: '/registrera'
      preLoaderRoute: typeof RegistreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vanliga-fragor': {
      id: '/vanliga-fragor'
      path: '/vanliga-fragor'
      fullPath: '/vanliga-fragor'
      preLoaderRoute: typeof VanligaFragorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agent-api-keys': {
      id: '/admin/agent-api-keys'
      path: '/admin/agent-api-keys'
      fullPath: '/admin/agent-api-keys'
      preLoaderRoute: typeof AdminAgentApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollnas/lakare-alm': {
      id: '/bollnas/lakare-alm'
      path: '/bollnas/lakare-alm'
      fullPath: '/bollnas/lakare-alm'
      preLoaderRoute: typeof BollnasLakareAlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/_layout': {
      id: '/consultant/_layout'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/forhandla': {
      id: '/consultant/forhandla'
      path: '/consultant/forhandla'
      fullPath: '/consultant/forhandla'
      preLoaderRoute: typeof ConsultantForhandlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/analytics': {
      id: '/dev/analytics'
      path: '/dev/analytics'
      fullPath: '/dev/analytics'
      preLoaderRoute: typeof DevAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/animationer': {
      id: '/dev/animationer'
      path: '/dev/animationer'
      fullPath: '/dev/animationer'
      preLoaderRoute: typeof DevAnimationerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/llms-check': {
      id: '/dev/llms-check'
      path: '/dev/llms-check'
      fullPath: '/dev/llms-check'
      preLoaderRoute: typeof DevLlmsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampanj/$role': {
      id: '/kampanj/$role'
      path: '/kampanj/$role'
      fullPath: '/kampanj/$role'
      preLoaderRoute: typeof KampanjRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/$reportId': {
      id: '/rapport/$reportId'
      path: '/rapport/$reportId'
      fullPath: '/rapport/$reportId'
      preLoaderRoute: typeof RapportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/allmansjukskoterska': {
      id: '/rapport/allmansjukskoterska'
      path: '/rapport/allmansjukskoterska'
      fullPath: '/rapport/allmansjukskoterska'
      preLoaderRoute: typeof RapportAllmansjukskoterskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/anestesisjukskoterska': {
      id: '/rapport/anestesisjukskoterska'
      path: '/rapport/anestesisjukskoterska'
      fullPath: '/rapport/anestesisjukskoterska'
      preLoaderRoute: typeof RapportAnestesisjukskoterskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/lakare-allmanmedicin': {
      id: '/rapport/lakare-allmanmedicin'
      path: '/rapport/lakare-allmanmedicin'
      fullPath: '/rapport/lakare-allmanmedicin'
      preLoaderRoute: typeof RapportLakareAllmanmedicinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/leg-sjukskoterska': {
      id: '/rapport/leg-sjukskoterska'
      path: '/rapport/leg-sjukskoterska'
      fullPath: '/rapport/leg-sjukskoterska'
      preLoaderRoute: typeof RapportLegSjukskoterskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/leg-ssk': {
      id: '/rapport/leg-ssk'
      path: '/rapport/leg-ssk'
      fullPath: '/rapport/leg-ssk'
      preLoaderRoute: typeof RapportLegSskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/legitimerad-sjukskoterska': {
      id: '/rapport/legitimerad-sjukskoterska'
      path: '/rapport/legitimerad-sjukskoterska'
      fullPath: '/rapport/legitimerad-sjukskoterska'
      preLoaderRoute: typeof RapportLegitimeradSjukskoterskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/sjukskoterska': {
      id: '/rapport/sjukskoterska'
      path: '/rapport/sjukskoterska'
      fullPath: '/rapport/sjukskoterska'
      preLoaderRoute: typeof RapportSjukskoterskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport/ssk': {
      id: '/rapport/ssk'
      path: '/rapport/ssk'
      fullPath: '/rapport/ssk'
      preLoaderRoute: typeof RapportSskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$region': {
      id: '/region/$region'
      path: '/region/$region'
      fullPath: '/region/$region'
      preLoaderRoute: typeof RegionRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultat/$leadId': {
      id: '/resultat/$leadId'
      path: '/resultat/$leadId'
      fullPath: '/resultat/$leadId'
      preLoaderRoute: typeof ResultatLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timpris/$role': {
      id: '/timpris/$role'
      path: '/timpris/$role'
      fullPath: '/timpris/$role'
      preLoaderRoute: typeof TimprisRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bekrafta-forslag': {
      id: '/api/public/bekrafta-forslag'
      path: '/api/public/bekrafta-forslag'
      fullPath: '/api/public/bekrafta-forslag'
      preLoaderRoute: typeof ApiPublicBekraftaForslagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-signup-confirmation': {
      id: '/api/public/send-signup-confirmation'
      path: '/api/public/send-signup-confirmation'
      fullPath: '/api/public/send-signup-confirmation'
      preLoaderRoute: typeof ApiPublicSendSignupConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/_layout/avtal': {
      id: '/consultant/_layout/avtal'
      path: '/avtal'
      fullPath: '/consultant/avtal'
      preLoaderRoute: typeof ConsultantLayoutAvtalRouteImport
      parentRoute: typeof ConsultantLayoutRoute
    }
    '/consultant/_layout/loneanalys': {
      id: '/consultant/_layout/loneanalys'
      path: '/loneanalys'
      fullPath: '/consultant/loneanalys'
      preLoaderRoute: typeof ConsultantLayoutLoneanalysRouteImport
      parentRoute: typeof ConsultantLayoutRoute
    }
    '/consultant/_layout/profil': {
      id: '/consultant/_layout/profil'
      path: '/profil'
      fullPath: '/consultant/profil'
      preLoaderRoute: typeof ConsultantLayoutProfilRouteImport
      parentRoute: typeof ConsultantLayoutRoute
    }
    '/lon/$specialty/$city': {
      id: '/lon/$specialty/$city'
      path: '/lon/$specialty/$city'
      fullPath: '/lon/$specialty/$city'
      preLoaderRoute: typeof LonSpecialtyCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsultantLayoutRouteChildren {
  ConsultantLayoutAvtalRoute: typeof ConsultantLayoutAvtalRoute
  ConsultantLayoutLoneanalysRoute: typeof ConsultantLayoutLoneanalysRoute
  ConsultantLayoutProfilRoute: typeof ConsultantLayoutProfilRoute
}

const ConsultantLayoutRouteChildren: ConsultantLayoutRouteChildren = {
  ConsultantLayoutAvtalRoute: ConsultantLayoutAvtalRoute,
  ConsultantLayoutLoneanalysRoute: ConsultantLayoutLoneanalysRoute,
  ConsultantLayoutProfilRoute: ConsultantLayoutProfilRoute,
}

const ConsultantLayoutRouteWithChildren =
  ConsultantLayoutRoute._addFileChildren(ConsultantLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AterstallLosenordRoute: AterstallLosenordRoute,
  FaktasidorRoute: FaktasidorRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  LoggaInRoute: LoggaInRoute,
  OnboardingRoute: OnboardingRoute,
  RegistreraRoute: RegistreraRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VanligaFragorRoute: VanligaFragorRoute,
  AdminAgentApiKeysRoute: AdminAgentApiKeysRoute,
  AdminHealthRoute: AdminHealthRoute,
  BollnasLakareAlmRoute: BollnasLakareAlmRoute,
  ConsultantLayoutRoute: ConsultantLayoutRouteWithChildren,
  ConsultantForhandlaRoute: ConsultantForhandlaRoute,
  DevAnalyticsRoute: DevAnalyticsRoute,
  DevAnimationerRoute: DevAnimationerRoute,
  DevLlmsCheckRoute: DevLlmsCheckRoute,
  KampanjRoleRoute: KampanjRoleRoute,
  RapportReportIdRoute: RapportReportIdRoute,
  RapportAllmansjukskoterskaRoute: RapportAllmansjukskoterskaRoute,
  RapportAnestesisjukskoterskaRoute: RapportAnestesisjukskoterskaRoute,
  RapportLakareAllmanmedicinRoute: RapportLakareAllmanmedicinRoute,
  RapportLegSjukskoterskaRoute: RapportLegSjukskoterskaRoute,
  RapportLegSskRoute: RapportLegSskRoute,
  RapportLegitimeradSjukskoterskaRoute: RapportLegitimeradSjukskoterskaRoute,
  RapportSjukskoterskaRoute: RapportSjukskoterskaRoute,
  RapportSskRoute: RapportSskRoute,
  RegionRegionRoute: RegionRegionRoute,
  ResultatLeadIdRoute: ResultatLeadIdRoute,
  TimprisRoleRoute: TimprisRoleRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicBekraftaForslagRoute: ApiPublicBekraftaForslagRoute,
  ApiPublicSendSignupConfirmationRoute: ApiPublicSendSignupConfirmationRoute,
  LonSpecialtyCityRoute: LonSpecialtyCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
